### ISSUE TITLE
Show job status text and provide humand readable text for job steps

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-platform#66]
Add a display of the job status text. This is crucial for communicating the status of an ERC.

Maybe as hover texts to the icons?

**Comment by MarkusKonk** [comment]
Which icons do you mean? You are talking about the overall status, not about those of the single steps, right?

**Comment by nuest** [comment]
No, I mean the single steps.

**Comment by MarkusKonk** [comment]
Still don't know which ICONS you mean. The green checks and red crosses? However, an example would be helpful. What information should be displayed?

**Comment by nuest** [comment]
Sorry for the confusion: I mean the :heavy_check_mark: and the **`X`** here:

![image](https://user-images.githubusercontent.com/1325054/30488316-427f774e-9a36-11e7-9197-78ea45309b9f.png)

The job actually provides a lot more information that just binary "success" and "failure", the currently unused [`text`](http://o2r.info/o2r-web-api/job/#view-single-job) property could help a lot to make clear what is going wrong. For example:

```json
{

    "id": "RUC4S",
    "compendium_id": "dBlnY",
    "steps": {
        "validate_bag": {
            "status": "failure",
            "text": "Command failed: bagit.py --validate /tmp/o2r/job/RUC4S\n2017-09-15 16:49:00,659 - INFO - /tmp/o2r/job/RUC4S is invalid: Oxum error.  Found 9 files and 58392 bytes on disk; expected 3 files and 317 bytes.\n",
            "end": "2017-09-15T14:49:00.676Z",
            "start": "2017-09-15T14:49:00.375Z"
        },
        "validate_compendium": {
            "status": "failure",
            "text": "compendium is invalid, but execution may continue",
            "end": "2017-09-15T14:49:00.695Z",
            "start": "2017-09-15T14:49:00.688Z"
        },
        "image_prepare": {
            "status": "success",
            "text": "payload with 67584 total bytes",
            "end": "2017-09-15T14:49:00.801Z",
            "start": "2017-09-15T14:49:00.709Z"
        },
        "image_build": {
            "status": "success",
            "text": "Step 1/6 : FROM alpine\nStep 2/6 : MAINTAINER <http://o2r.info>\n ---> 39dc3563c010\nStep 3/6 : ENV HOST 127.0.0.1\n ---> de6bb0cbae09\n ---> 3bc4c7353b5e\nSuccessfully tagged bagtainer:RUC4S\n",
            "end": "2017-09-15T14:49:01.619Z",
            "start": "2017-09-15T14:49:00.806Z"
        },
        "image_execute": {
            "status": "success",
            "text": "PING 127.0.0.1 (127.0.0.1): 56 data bytes\r\n64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.050 ms\r\n64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.066 ms\r\n64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.045 ms\r\n64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.077 ms\r\n64 bytes from 127.0.0.1: seq=4 ttl=64 time=0.122 ms\r\n64 bytes from 127.0.0.1: seq=5 ttl=64 time=0.147 ms\r\n64 bytes from 127.0.0.1: seq=6 ttl=64 time=0.061 ms\r\n64 bytes from 127.0.0.1: seq=7 ttl=64 time=0.058 ms\r\n64 bytes from 127.0.0.1: seq=8 ttl=64 time=0.061 ms\r\n64 bytes from 127.0.0.1: seq=9 ttl=64 time=0.045 ms\r\n64 bytes from 127.0.0.1: seq=10 ttl=64 time=0.043 ms\r\n64 bytes from 127.0.0.1: seq=11 ttl=64 time=0.052 ms\r\n64 bytes from 127.0.0.1: seq=12 ttl=64 time=0.073 ms\r\n64 bytes from 127.0.0.1: seq=13 ttl=64 time=0.061 ms\r\n64 bytes from 127.0.0.1: seq=14 ttl=64 time=0.066 ms\r\n64 bytes from 127.0.0.1: seq=15 ttl=64 time=0.045 ms\r\n64 bytes from 127.0.0.1: seq=16 ttl=64 time=0.052 ms\r\n64 bytes from 127.0.0.1: seq=17 ttl=64 time=0.073 ms\r\n64 bytes from 127.0.0.1: seq=18 ttl=64 time=0.046 ms\r\n64 bytes from 127.0.0.1: seq=19 ttl=64 time=0.043 ms\r\n64 bytes from 127.0.0.1: seq=20 ttl=64 time=0.044 ms\r\n64 bytes from 127.0.0.1: seq=21 ttl=64 time=0.041 ms\r\n64 bytes from 127.0.0.1: seq=22 ttl=64 time=0.050 ms\r\n64 bytes from 127.0.0.1: seq=23 ttl=64 time=0.078 ms\r\n64 bytes from 127.0.0.1: seq=24 ttl=64 time=0.051 ms\r\n64 bytes from 127.0.0.1: seq=25 ttl=64 time=0.043 ms\r\n64 bytes from 127.0.0.1: seq=26 ttl=64 time=0.049 ms\r\n64 bytes from 127.0.0.1: seq=27 ttl=64 time=0.063 ms\r\n64 bytes from 127.0.0.1: seq=28 ttl=64 time=0.049 ms\r\n64 bytes from 127.0.0.1: seq=29 ttl=64 time=0.052 ms\r\n\r\n--- 127.0.0.1 ping statistics ---\r\n30 packets transmitted, 30 packets received, 0% packet loss\r\nround-trip min/avg/max = 0.041/0.060/0.147 ms\r\n",
            "statuscode": 0,
            "end": "2017-09-15T14:49:31.758Z",
            "start": "2017-09-15T14:49:01.702Z"
        },
        "cleanup": {
            "status": "success",
            "text": "Done: removed container.\nDone: kept image with tag bagtainer:RUC4S for job RUC4S\nDone: deleted tmp payload file.",
            "end": "2017-09-15T14:49:31.803Z",
            "start": "2017-09-15T14:49:31.761Z"
        }
    },
    "status": "failure",
    "files": { }
}
```

## Tasks

- [ ] give user access to `text` of a job step (somehow... the hover text might actually not be a good idea)
- [ ] provide a "API access" link directly to the JSON of the job (useful for debugging, useful for platform transparency, see #94)
- [ ] show only the start date of the job, and show time periods (e.g. "7 s", "5 minutes") for the step durations, see https://momentjs.com/docs/#/durations/humanize/

## Optional tasks

- [ ] human-readable (no "_") names for the different job steps, see http://o2r.info/o2r-web-api/job/#steps-of-a-job (if you create a map or some data structure for that, I can add the names). This should be flexible, because there soon will be more job steps.

**Comment by MarkusKonk** [comment]
Alright, that makes sense.

**Comment by jansule** [comment]
@nuest job status text is only provided through an api call. For dynamically updating the status we are using sockets. Sockets only provide information about the status, not the status text. See example response of socket here:
```json
{
  "partial": true,
  "id": "9y9D1",
  "steps": {
    "cleanup": {
      "status": "running"
    }
  },
  "updatedAt": "2017-10-18T09:59:36.759Z"
}
```

**Comment by nuest** [comment]
I'm getting mixed messages here... is this fixed now or not?

I'd gladly add the status text to the socket messages, it should be there.

**Comment by jansule** [comment]
@nuest At the moment we display only the logs we get from the api call, not the sockets. This is enough for displaying information of the last finished status. But it is not sufficient for adding logs to running jobs. Therefore, it would be nice if the status text could be added to the sockets.
@MarkusKonk what do you think about this? Are logs for running jobs required?

**Comment by nuest** [comment]
I think they are very useful for currently running jobs, because they may include status messages the help me estimate how long the job will take. Since we don't have a formal specification on those yet (we have no idea...), we should at least allow humans to interpret the job log.

Let me know if this is urgent for you, then I'll put it on my list.
